"""Cortical summary statistics; adapted from the supplied @saratheriver loader."""

from pathlib import Path
import pandas as pd


_FILES = {
    '22q': {
        'CortThick_case_vs_controls': '22q_case-controls_CortThick.csv',
        'CortSurf_case_vs_controls': '22q_case-controls_CortSurf.csv',
        'CortThick_psychP_vs_psychN': '22q_psych+-psych-_CortThick.csv',
        'CortSurf_psychP_vs_psychN': '22q_psych+-psych-_CortSurf.csv',
    },
    'adhd': {
        'CortThick_case_vs_controls_allages': 'adhdallages_case-controls_CortThick.csv',
        'CortSurf_case_vs_controls_allages': 'adhdallages_case-controls_CortSurf.csv',
        'CortThick_case_vs_controls_adult': 'adhdadult_case-controls_CortThick.csv',
        'CortSurf_case_vs_controls_adult': 'adhdadult_case-controls_CortSurf.csv',
        'CortThick_case_vs_controls_adolescent': 'adhdadolescent_case-controls_CortThick.csv',
        'CortSurf_case_vs_controls_adolescent': 'adhdadolescent_case-controls_CortSurf.csv',
        'CortThick_case_vs_controls_pediatric': 'adhdpediatric_case-controls_CortThick.csv',
        'CortSurf_case_vs_controls_pediatric': 'adhdpediatric_case-controls_CortSurf.csv',
    },
    'anorexia': {
        'CortThick_anorexia_case_controls': 'anorexia_case-controls_CortThick.csv',
        'CortSurf_anorexia_case_controls': 'anorexia_case-controls_CortSurf.csv',
        'CortThick_anorexia_case_controls_wGlo': 'anorexia_case-controls_CortThick_wGlo.csv',
        'CortSurf_anorexia_case_controls_wGlo': 'anorexia_case-controls_CortSurf_wGlo.csv',
        'CortThick_anorexia_acAN_controls': 'anorexia_acAN-controls_CortThick.csv',
        'CortSurf_anorexia_acAN_controls': 'anorexia_acAN-controls_CortSurf.csv',
        'CortThick_anorexia_acAN_controls_wGlo': 'anorexia_acAN-controls_CortThick_wGlo.csv',
        'CortSurf_anorexia_acAN_controls_wGlo': 'anorexia_acAN-controls_CortSurf_wGlo.csv',
        'CortThick_anorexia_acANpwrAN_wGlo': 'anorexia_acAN-pwrAN_CortThick_wGlo.csv',
        'CortSurf_anorexia_acANpwrAN': 'anorexia_acAN-pwrAN_CortSurf.csv',
        'CortThick_anorexia_acANpwrAN': 'anorexia_acAN-pwrAN_CortThick.csv',
        'CortSurf_anorexia_acANpwrAN_wGlo': 'anorexia_acAN-pwrAN_CortSurf_wGlo.csv',
        'CortSurf_anorexia_pwrANcontrols_wGlo': 'anorexia_pwrAN-controls_CortSurf_wGlo.csv',
        'CortSurf_anorexia_pwrAN_controls': 'anorexia_pwrAN-controls_CortSurf.csv',
        'CortThick_anorexia_pwrAN_controls_wGlo': 'anorexia_pwrAN-controls_CortThick_wGlo.csv',
        'CortThick_anorexia_pwrAN_controls': 'anorexia_pwrAN-controls_CortThick.csv',
    },
    'antisocial': {
        'CortThick_case_controls_antisocial': 'Antisocial_case-controls_CortThick.csv',
        'CortSurf_case_controls_antisocial': 'Antisocial_case-controls_CortSurf.csv',
    },
    'asymmetry': {
        'CortThick_asymm_ICVeffects': 'Asymm_ICVeffects_CorticalThick.csv',
        'CortSurf_asymm_ICVeffects': 'Asymm_ICVeffects _CorticalSurf.csv',
        'CortThick_asymm_handedness-diff': 'Asymm_Handedness-diff_CorticalThick.csv',
        'CortSurf_asymm_handedness-diff': 'Asymm_Handedness-diff_CorticalSurf.csv',
        'CortThick_asymm_ageeffects': 'Asymm_Ageeffects_CorticalThick.csv',
        'CortSurf_asymm_ageeffects': 'Asymm_Ageeffects_CorticalSurf.csv',
        'CortThick_asymm_ageeffects_20years': 'Asymm_Ageeffects_CorticalThick_20years.csv',
        'CortSurf_asymm_ageeffects_20years': 'Asymm_Ageeffects_CorticalSurf_20years.csv',
        'CortThick_asymm_sexeffects': 'Asymm_Sexeffects_CorticalThick.csv',
        'CortSurf_asymm_sexeffects': 'Asymm_Sexeffects_CorticalSurf.csv',
        'CortThick_asymm_population_level': 'Asymm_population-level_asymmetry_CortThick.csv',
        'CortSurf_asymm_population_level': 'Asymm_population-level_asymmetry_CortSurf.csv',
    },
    'asd': {
        'CortThick_case_vs_controls_meta_analysis': 'asd_meta-analysis_case-controls_CortThick.csv',
        'CortThick_case_vs_controls_mega_analysis': 'asd_mega-analysis_case-controls_CortThick.csv',
    },
    'bipolar': {
        'CortThick_case_vs_controls_adult': 'bd_case-controls_CortThick_adult.csv',
        'CortSurf_case_vs_controls_adult': 'bd_case-controls_CortSurf_adult.csv',
        'CortThick_typeI_vs_typeII_adult': 'bd_typeI-typeII_CortThick_adult.csv',
        'CortSurf_typeI_vs_typeII_adult': 'bd_typeI-typeII_CortSurf_adult.csv',
        'CortThick_case_vs_controls_adolescent': 'bd_case-controls_CortThick_adolescent.csv',
        'CortSurf_case_vs_controls_adolescent': 'bd_case-controls_CortSurf_adolescent.csv',
        'CortThick_typeI_vs_typeII_adolescent': 'bd_typeI-typeII_CortThick_adolescent.csv',
        'CortSurf_typeI_vs_typeII_adolescent': 'bd_typeI-typeII_CortSurf_adolescent.csv',
    },
    'depression': {
        'CortThick_case_vs_controls_adult': 'mddadult_case-controls_CortThick.csv',
        'CortSurf_case_vs_controls_adult': 'mddadult_case-controls_CortSurf.csv',
        'CortThick_case_vs_controls_adult_firstepisode': 'mddadult_case-controls_CortThick_firstepisode.csv',
        'CortSurf_case_vs_controls_adult_firstepisode': 'mddadult_case-controls_CortSurf_firstepisode.csv',
        'CortThick_case_vs_controls_adult_recurrent': 'mddadult_case-controls_CortThick_recurrent.csv',
        'CortSurf_case_vs_controls_adult_recurrent': 'mddadult_case-controls_CortSurf_recurrent.csv',
        'CortThick_firstepisode_vs_recurrent_adult': 'mddadult_firstepisode-recurrent_CortThick.csv',
        'CortSurf_firstepisode_vs_recurrent_adult': 'mddadult_firstepisode-recurrent_CortSurf.csv',
        'CortThick_case_vs_controls_adult_early': 'mddadult_case-controls_CortThick_early.csv',
        'CortSurf_case_vs_controls_adult_early': 'mddadult_case-controls_CortSurf_early.csv',
        'CortThick_case_vs_controls_adult_late': 'mddadult_case-controls_CortThick_late.csv',
        'CortSurf_case_vs_controls_adult_late': 'mddadult_case-controls_CortSurf_late.csv',
        'CortThick_early_vs_late_adult': 'mddadult_early-late_CortThick.csv',
        'CortSurf_early_vs_late_adult': 'mddadult_early-late_CortSurf.csv',
        'CortThick_case_vs_controls_adolescent': 'mddadolescent_case-controls_CortThick.csv',
        'CortSurf_case_vs_controls_adolescent': 'mddadolescent_case-controls_CortSurf.csv',
        'CortThick_case_vs_controls_adolescent_firstepisode': 'mddadolescent_case-controls_CortThick_firstepisode.csv',
        'CortSurf_case_vs_controls_adolescent_firstepisode': 'mddadolescent_case-controls_CortSurf_firstepisode.csv',
        'CortThick_case_vs_controls_adolescent_recurrent': 'mddadolescent_case-controls_CortThick_recurrent.csv',
        'CortSurf_case_vs_controls_adolescent_recurrent': 'mddadolescent_case-controls_CortSurf_recurrent.csv',
        'CortThick_firstepisode_vs_recurrent_adolescent': 'mddadolescent_firstepisode-recurrent_CortThick.csv',
        'CortSurf_firstepisode_vs_recurrent_adolescent': 'mddadolescent_firstepisode-recurrent_CortSurf.csv',
    },
    'epilepsy': {
        'CortThick_case_vs_controls_allepilepsy': 'allepi_case-controls_CortThick.csv',
        'CortThick_case_vs_controls_gge': 'gge_case-controls_CortThick.csv',
        'CortThick_case_vs_controls_ltle': 'tlemtsl_case-controls_CortThick.csv',
        'CortThick_case_vs_controls_rtle': 'tlemtsr_case-controls_CortThick.csv',
        'CortThick_case_vs_controls_allotherepilepsy': 'allotherepi_case-controls_CortThick.csv',
    },
    'lifespan': {
        'CortThick_agevsthick_all_3to29': 'lifespan_CortThick_age_vs_thickness_all3-29years.csv',
        'CortThick_agevsthick_all_30to59': 'lifespan_CortThick_age_vs_thickness_all30-59years.csv',
        'CortThick_agevsthick_all_60to90': 'lifespan_CortThick_age_vs_thickness_all60-90years.csv',
        'CortThick_agevsthick_F_3to29': 'lifespan_CortThick_age_vs_thickness_F3-29years.csv',
        'CortThick_agevsthick_F_30to59': 'lifespan_CortThick_age_vs_thickness_F30-59years.csv',
        'CortThick_agevsthick_F_60to90': 'lifespan_CortThick_age_vs_thickness_F60-90years.csv',
        'CortThick_agevsthick_M_3to29': 'lifespan_CortThick_age_vs_thickness_M3-29years.csv',
        'CortThick_agevsthick_M_30to59': 'lifespan_CortThick_age_vs_thickness_M30-59years.csv',
        'CortThick_agevsthick_M_60to90': 'lifespan_CortThick_age_vs_thickness_M60-90years.csv',
    },
    'ocd': {
        'CortThick_case_vs_controls_adult': 'ocdadults_case-controls_CortThick.csv',
        'CortSurf_case_vs_controls_adult': 'ocdadults_case-controls_CortSurf.csv',
        'CortThick_medicatedcase_vs_controls_adult': 'ocdadults_medicatedcase-controls_CortThick.csv',
        'CortSurf_medicatedcase_vs_controls_adult': 'ocdadults_medicatedcase-controls_CortSurf.csv',
        'CortThick_case_vs_controls_pediatric': 'ocdpediatric_case-controls_CortThick.csv',
        'CortSurf_case_vs_controls_pediatric': 'ocdpediatric_case-controls_CortSurf.csv',
        'CortThick_medicatedcase_vs_controls_pediatric': 'ocdpediatric_medicatedcase-controls_CortThick.csv',
        'CortSurf_medicatedcase_vs_controls_pediatric': 'ocdpediatric_medicatedcase-controls_CortSurf.csv',
    },
    'parkinsons': {
        'CortSurf_HY1PDvsCN': 'parkinsons_case-controls_CortSurf_HY1PDvsCN.csv',
        'CortSurf_HY1PDvsHY2PD': 'parkinsons_case-controls_CortSurf_HY1PDvsHY2PD.csv',
        'CortSurf_HY2PDvsH3YPD': 'parkinsons_case-controls_CortSurf_HY2PDvsHY3PD.csv',
        'CortSurf_HY2PDvsCN': 'parkinsons_case-controls_CortSurf_HY2PDvsCN.csv',
        'CortSurf_HY3PDvsHY4PDandH5YPD': 'parkinsons_case-controls_CortSurf_HY3PDvsHY4PDandHY5PD.csv',
        'CortSurf_HY3PDvsCN': 'parkinsons_case-controls_CortSurf_HY3PDvsCN.csv',
        'CortSurf_HY4PDandHY5PDvsCN': 'parkinsons_case-controls_CortSurf_HY4PDandHY5PDvsCN.csv',
        'CortSurf_MoCAvsCN': 'parkinsons_case-controls_CortSurf_MoCAvsCN.csv',
        'CortSurf_PDvsCN': 'parkinsons_case-controls_CortSurf_PDvsCN.csv',
        'CortThick_HY1PDvsCN': 'parkinsons_case-controls_CortThick_HY1PDvsCN.csv',
        'CortThick_HY1PDvsHY2PD': 'parkinsons_case-controls_CortThick_HY1PDvsHY2PD.csv',
        'CortThick_HY2PDvsHY3PD': 'parkinsons_case-controls_CortThick_HY2PDvsHY3PD.csv',
        'CortThick_HY2PDvsCN': 'parkinsons_case-controls_CortThick_HY2PDvsCN.csv',
        'CortThick_HY3PDvsHY4PDandHY5PD': 'parkinsons_case-controls_CortThick_HY3PDvsHY4PDandHY5PD.csv',
        'CortThick_HY3PDvsCN': 'parkinsons_case-controls_CortThick_HY3PDvsCN.csv',
        'CortThick_HY4PDandHY5PDvsCN': 'parkinsons_case-controls_CortThick_HY4PDandHY5PDvsCN.csv',
        'CortThick_MoCAvsCN': 'parkinsons_case-controls_CortThick_MoCAvsCN.csv',
        'CortThick_PDvsCN': 'parkinsons_case-controls_CortThick_PDvsCN.csv',
    },
    'psychosis': {
        'CortThick_CHR_vs_HC_postCombat_mega': 'psychosis_case-controls_CortThick_ICV.csv',
        'CortSurf_CHR_vs_HC_postCombat_mega': 'psychosis_case-controls_CortSurf_ICV.csv',
        'CortThick_CHR_vs_HC_postCombat_ICVexcluded_mega': 'psychosis_case-controls_CortThick_postComBatmegaanalysis_ICVex.csv',
        'CortSurf_CHR_vs_HC_postCombat_ICVexcluded_mega': 'psychosis_case-controls_CortSurf_postComBatmegaanalysis_ICVex.csv',
        'CortThick_CHR_Subgroup_APS_vs_HC': 'psychosis_case-controls_CortThick_CHR_Subgroup_APSvsCN.csv',
        'CortSurf_CHR_Subgroup_APS_vs_HC': 'psychosis_case-controls_CortSurf_CHR_Subgroup_APSvsCN.csv',
        'CortThick_CHR_Subgroup_BIPS_vs_HC': 'psychosis_case-controls_CortThick_CHR_Subgroup_BIPSvsCN.csv',
        'CortSurf_CHR_Subgroup_BIPS_vs_HC': 'psychosis_case-controls_CortSurf_CHR_Subgroup_BIPSvcCN.csv',
        'CortThick_CHR_Subgroup_GRD_vs_HC': 'psychosis_case-controls_CortThick_CHR_Subgroup_GRDvsCN.csv',
        'CortSurf_CHR_Subgroup_GRD_vs_HC': 'psychosis_case-controls_CortSurf_CHR_Subgroup_GRDvsCN.csv',
        'CortThick_CHR_Subgroup_APS_vs_BIPS': 'psychosis_case-controls_CortThick_CHR_Subgroup_APSvsBIPS.csv',
        'CortSurf_CHR_Subgroup_APS_vs_BIPS': 'psychosis_case-controls_CortSurf_CHR_Subgroup_APSvsBIPS.csv',
        'CortThick_CHR_Subgroup_GRD_vs_BIPS': 'psychosis_case-controls_CortThick_CHR_Subgroup_GRDvsBIPS.csv',
        'CortSurf_CHR_Subgroup_GRD_vs_BIPS': 'psychosis_case-controls_CortSurf_CHR_Subgroup_GRDvsBIPS.csv',
        'CortThick_CHR_Subgroup_APS_vs_GRD': 'psychosis_case-controls_CortThick_CHR_Subgroup_APSvsGRD.csv',
        'CortSurf_CHR_Subgroup_APS_vs_GRD': 'psychosis_case-controls_CortSurf_CHR_Subgroup_APSvsGRD.csv',
        'CortThick_APS_Subgroup_APS_vs_HC': 'psychosis_case-controls_CortThick_APS_Subgroup_APSvsCN.csv',
        'CortSurf_APS_Subgroup_APS_vs_HC': 'psychosis_case-controls_CortSurf_APS_Subgroup_APSvsCN.csv',
        'CortThick_APS_Subgroup_APS_vs_noAPS': 'psychosis_case-controls_CortThick_APS_Subgroup_APSvsnoAPS.csv',
        'CortSurf_APS_Subgroup_APS_vs_noAPS': 'psychosis_case-controls_CortSurf_APS_Subgroup_APSvsnoAPS.csv',
        'CortThick_APS_Subgroup_noAPS_vs_HC': 'psychosis_case-controls_CortThick_APS_Subgroup_noAPSvsCN.csv',
        'CortSurf_APS_Subgroup_noAPS_vs_HC': 'psychosis_case-controls_CortSurf_APS_Subgroup_noAPSvsCN.csv',
        'CortThick_BIPS_Subgroup_BIPS_vs_HC': 'psychosis_case-controls_CortThick_BIPS_Subgroup_BIPSvsCN.csv',
        'CortSurf_BIPS_Subgroup_BIPS_vs_HC': 'psychosis_case-controls_CortSurf_BIPS_Subgroup_BIPSvsCN.csv',
        'CortThick_BIPS_Subgroup_BIPS_vs_noBIPS': 'psychosis_case-controls_CortThick_BIPS_Subgroup_BIPSvsnoBIPS.csv',
        'CortSurf_BIPS_Subgroup_BIPS_vs_noBIPS': 'psychosis_case-controls_CortSurf_BIPS_Subgroup_BIPSvsnoBIPS.csv',
        'CortThick_BIPS_Subgroup_noBIPS_vs_HC': 'psychosis_case-controls_CortThick_BIPS_Subgroup_noBIPSvsCN.csv',
        'CortSurf_BIPS_Subgroup_noBIPS_vs_HC': 'psychosis_case-controls_CortSurf_BIPS_Subgroup_noBIPSvsCN.csv',
        'CortThick_GRD_Subgroup_GRD_vs_HC': 'psychosis_case-controls_CortThick_GRD_Subgroup_GRDvsCN.csv',
        'CortSurf_GRD_Subgroup_GRD_vs_HC': 'psychosis_case-controls_CortSurf_GRD_Subgroup_GRDvsCN.csv',
        'CortThick_GRD_Subgroup_GRD_vs_noGRD': 'psychosis_case-controls_CortThick_GRD_Subgroup_GRDvsnoGRD.csv',
        'CortSurf_GRD_Subgroup_GRD_vs_noGRD': 'psychosis_case-controls_CortSurf_GRD_Subgroup_GRDvsnoGRD.csv',
        'CortThick_GRD_Subgroup_noGRD_vs_HC': 'psychosis_case-controls_CortThick_GRD_Subgroup_noGRDvsCN.csv',
        'CortSurf_GRD_Subgroup_noGRD_vs_HC': 'psychosis_case-controls_CortSurf_GRD_Subgroup_noGRDvsCN.csv',
        'CortThick_CHR_PS_Subgroup_PSpos_vs_HC': 'psychosis_case-controls_CortThick_CHR-PS+vsCN_postComBatmegaanalysis.csv',
        'CortSurf_CHR_PS_Subgroup_PSpos_vs_HC': 'psychosis_case-controls_CortSurf_CHR-PS+vsCN_postComBatmegaanalysis.csv',
        'CortThick_CHR_PS_Subgroup_PSneg_vs_HC': 'psychosis_case-controls_CortThick_CHR-PS-vsCN_postComBatmegaanalysis.csv',
        'CortSurf_CHR_PS_Subgroup_PSneg_vs_HC': 'psychosis_case-controls_CortSurf_CHR-PS-vsCN_postComBatmegaanalysis.csv',
        'CortThick_CHR_PS_Subgroup_PSpos_vs_PSneg': 'psychosis_case-controls_CortThick_CHR-PS+vsCHR-PS-_postComBatmegaanalysis.csv',
        'CortSurf_CHR_PS_Subgroup_PSpos_vs_PSneg': 'psychosis_case-controls_CortSurf_CHR-PS+vsCHR-PS-_postComBatmegaanalysis.csv',
    },
    'schizophrenia': {
        'CortThick_case_vs_controls': 'scz_case-controls_CortThick.csv',
        'CortSurf_case_vs_controls': 'scz_case-controls_CortSurf.csv',
        'Schizo_CortThick': 'Schizophrenia_case-controls_CortThick.csv',
    },
    'schizotypy': {
        'CortThick_Controlling_SmokingStatus': 'schizotypy_SmokingCN.csv',
        'CortThick_Smoking_Subgroup': 'schizotypy_SmokingSubgroup.csv',
        'CortSurf_noSurfAreaCovariate': 'schizotypy_CortSurf_noSurfAreaCovariate.csv',
        'CortSurf_SurfAreaCovariate': 'schizotypy_CortSurf_SurfAreaCovariate.csv',
        'CortThick_noThicknessCovariate': 'schizotypy_CortThick_noThicknessCovariate.csv',
        'CortThick_ThicknessCovariate': 'schizotypy_CortThick_ThicknessCovariate.csv',
    },
}



def load_summary_stats(data_dir=None):
    """Return {disorder: {name: DataFrame}} for all cortical summary statistics.

    By default, read from the summary_statistics folder beside this script.
    Set data_dir to that folder's path when the CSVs are stored elsewhere.
    """
    folder = Path(data_dir) if data_dir is not None else Path(__file__).parent / "summary_statistics"
    return {
        disorder: {
            key: pd.read_csv(folder / filename, on_bad_lines="skip")
            for key, filename in files.items()
        }
        for disorder, files in _FILES.items()
    }
